# Script principal para la sepración de las áreas para los sistemas de la IEEE

In [1]:
# importamos las librerías necesarias
import pandapower as pp, pandapower.networks as pn
from _source import sep_system

In [26]:
# cramos el área A
bus_area_A = [1,2,30,37,25,3,18,26,17,27,28,29,38]
red_A = sep_system.separate(pn.case39(), bus_area_A)
red_A

This pandapower network includes the following parameter tables:
   - bus (13 elements)
   - load (8 elements)
   - gen (3 elements)
   - ext_grid (1 element)
   - line (11 elements)
   - trafo (3 elements)
   - poly_cost (3 elements)
   - bus_geodata (13 elements)

In [23]:
red_A.gen.at[0, 'slack'] = True
red_A.gen.at[0, 'slack_weight'] = 1.0
red_A.gen

,bus,controllable,in_service,name,p_mw,scaling,sn_mva,type,vm_pu,slack,max_p_mw,min_p_mw,max_q_mvar,min_q_mvar,slack_weight
0,29,True,True,None,250.0,1.0,NaN,None,1.0499,True,1040.0,0.0,400.0,140.0,1.0
6,36,True,True,None,540.0,1.0,NaN,None,1.0275,False,564.0,0.0,250.0,0.0,0.0
7,37,True,True,None,830.0,1.0,NaN,None,1.0265,False,865.0,0.0,300.0,-150.0,0.0

In [24]:
pp.runpp(red_A)

numba cannot be imported and numba functions are disabled.
Probably the execution is slow.
Please install numba to gain a massive speedup.
(or if you prefer slow execution, set the flag numba=False to avoid this warning!)

In [25]:
red_A.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,-97.600000,-44.200000,97.899187,-30.802262,0.299187,-75.002262,0.169614,0.161569,0.169614,1.057106,-5.462070,1.063016,-3.425556,16.892336
2,436.867551,-7.438089,-434.671320,4.008212,2.196231,-3.429876,0.687849,0.687253,0.687849,1.063016,-3.425556,1.058481,-6.781908,82.205908
3,-175.319727,100.898861,177.961773,-114.196473,2.642046,-13.297612,0.318446,0.331966,0.331966,1.063016,-3.425556,1.065945,-2.276756,39.673788
5,112.671320,-6.408212,-112.546377,-15.994710,0.124943,-22.402922,0.178423,0.180028,0.180028,1.058481,-6.781908,1.056704,-7.546421,21.515429
24,45.466851,-0.579491,-45.453623,-14.005290,0.013228,-14.584781,0.071955,0.075323,0.075323,1.057527,-7.357704,1.056704,-7.546421,7.501684
25,-45.466851,0.579491,45.494886,-36.089726,0.028035,-35.510236,0.071955,0.092108,0.092108,1.057527,-7.357704,1.055077,-6.941396,9.173282
30,136.373158,-34.594223,-135.848839,-20.337693,0.524319,-54.931917,0.220880,0.216047,0.220880,1.065945,-2.276756,1.064000,-4.509722,21.998105
31,327.844078,26.678297,-326.494886,-39.410274,1.349192,-12.731977,0.517344,0.521619,0.521619,1.064000,-4.509722,1.055077,-6.941396,51.949590
32,-140.686313,-9.733869,141.483113,-69.171422,0.796800,-78.905292,0.221803,0.249506,0.249506,1.064000,-4.509722,1.056292,-1.032522,24.849021
33,-190.308927,-13.606734,192.232774,-80.720440,1.923848,-94.327174,0.300086,0.330977,0.330977,1.064000,-4.509722,1.054175,1.708306,32.963009
34,-347.483113,41.571423,349.036761,-52.540862,1.553648,-10.969440,0.554442,0.560330,0.560330,1.056292,-1.032522,1.054175,1.708306,55.804934

In [45]:
red = pn.case39()
bus_A_ = list(red.bus["name"])+[1,3,17]
for value in bus_area_A:
    bus_A_.remove(value)

print(bus_A_)

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 31, 32, 33, 34, 35, 36, 39, 1, 3, 17]

In [ ]:
pp.runpp(red)
red.res_line

In [46]:
# cramos el área A -
red_A_ = sep_system.separate(pn.case39(), bus_A_)
red_A_

This pandapower network includes the following parameter tables:
   - bus (29 elements)
   - load (15 elements)
   - gen (6 elements)
   - line (24 elements)
   - trafo (8 elements)
   - poly_cost (9 elements)
   - bus_geodata (29 elements)

In [50]:
red_A_.gen.at[1, 'slack'] = True
red_A_.gen.at[1, 'slack_weight'] = 1.0
red_A_.gen

,bus,controllable,in_service,name,p_mw,scaling,sn_mva,type,vm_pu,slack,max_p_mw,min_p_mw,max_q_mvar,min_q_mvar,slack_weight
1,31,True,True,None,650.0,1.0,NaN,None,0.9841,True,725.0,0.0,300.0,150.0,1.0
2,32,True,True,None,632.0,1.0,NaN,None,0.9972,False,652.0,0.0,250.0,0.0,0.0
3,33,True,True,None,508.0,1.0,NaN,None,1.0123,False,508.0,0.0,167.0,0.0,0.0
4,34,True,True,None,650.0,1.0,NaN,None,1.0494,False,687.0,0.0,300.0,-100.0,0.0
5,35,True,True,None,560.0,1.0,NaN,None,1.0636,False,580.0,0.0,240.0,0.0,0.0
8,38,True,True,None,1000.0,1.0,NaN,None,1.0300,False,1100.0,0.0,300.0,-100.0,0.0

In [48]:
red_A_.bus

    in_service  max_vm_pu  min_vm_pu name type  vn_kv zone
0         True       1.06       0.94    1    b  345.0  2.0
2         True       1.06       0.94    3    b  345.0  2.0
3         True       1.06       0.94    4    b  345.0  1.0
4         True       1.06       0.94    5    b  345.0  1.0
5         True       1.06       0.94    6    b  345.0  1.0
6         True       1.06       0.94    7    b  345.0  1.0
7         True       1.06       0.94    8    b  345.0  1.0
8         True       1.06       0.94    9    b  345.0  1.0
9         True       1.06       0.94   10    b  345.0  1.0
10        True       1.06       0.94   11    b  345.0  1.0
11        True       1.06       0.94   12    b  345.0  1.0
12        True       1.06       0.94   13    b  345.0  1.0
13        True       1.06       0.94   14    b  345.0  1.0
14        True       1.06       0.94   15    b  345.0  3.0
15        True       1.06       0.94   16    b  345.0  3.0
16        True       1.06       0.94   17    b  345.0  2.0
18        True       1.06       0.94   19    b  345.0  3.0
19        True       1.06       0.94   20    b  345.0  3.0
20        True       1.06       0.94   21    b  345.0  3.0
21        True       1.06       0.94   22    b  345.0  3.0
22        True       1.06       0.94   23    b  345.0  3.0
23        True       1.06       0.94   24    b  345.0  3.0
30        True       1.06       0.94   31    b  345.0  1.0
31        True       1.06       0.94   32    b  345.0  1.0
32        True       1.06       0.94   33    b  345.0  3.0
33        True       1.06       0.94   34    b  345.0  3.0
34        True       1.06       0.94   35    b  345.0  3.0
35        True       1.06       0.94   36    b  345.0  3.0
38        True       1.06       0.94   39    b  345.0  1.0

In [56]:
pp.runpp(red_A_)

numba cannot be imported and numba functions are disabled.
Probably the execution is slow.
Please install numba to gain a massive speedup.
(or if you prefer slow execution, set the flag numba=False to avoid this warning!)

LoadflowNotConverged: Power Flow nr did not converge after 10 iterations!

In [57]:
pp.create_ward(red_A_, 0, 76.099968, -3.89266 , 76.099968, -3.89266)

1

In [58]:
red_A_.res_ward

   p_mw  q_mvar  vm_pu
0   NaN     NaN    NaN

In [59]:
pp.runpp(red_A_)

numba cannot be imported and numba functions are disabled.
Probably the execution is slow.
Please install numba to gain a massive speedup.
(or if you prefer slow execution, set the flag numba=False to avoid this warning!)

LoadflowNotConverged: Power Flow nr did not converge after 10 iterations!